# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cspamdetector\"\x1a\n\x07SpamReq\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x07SpamRes\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32G\n\x0cSpamDetector\x12\x37\n\x07Predict\x12\x15.spamdetector.SpamReq\x1a\x15.spamdetector.SpamResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPAMREQ']._serialized_start=31
  _globals['_SPAMREQ']._serialized_end=57
  _globals['_SPAMRES']._serialized_start=59
  _globals['_SPAMRES']._serialized_end=84
  _globals['_SPAMDETECTOR']._serialized_start=86
  _globals['_SPAMDETECTOR']._serialized_end=157
# @@protoc_insertion_point(module_scope)
